qsub -o ~/HPC/code/parallel/logs/fast/n8 -e ~/HPC/code/parallel/logs/fast/n8 -v ARG1=5000,ARG2=8,ARG3=0 execute.sh
qsub -o ~/HPC/code/parallel/logs/fast/n8 -e ~/HPC/code/parallel/logs/fast/n8 -v ARG1=5000,ARG2=8,ARG3=0 execute.sh
qsub -o ~/HPC/code/parallel/logs/fast/n8 -e ~/HPC/code/parallel/logs/fast/n8 -v ARG1=7500,ARG2=8,ARG3=0 execute.sh
qsub -o ~/HPC/code/parallel/logs/fast/n8 -e ~/HPC/code/parallel/logs/fast/n8 -v ARG1=7500,ARG2=8,ARG3=0 execute.sh
qsub -o ~/HPC/code/parallel/logs/fast/n8 -e ~/HPC/code/parallel/logs/fast/n8 -v ARG1=7500,ARG2=8,ARG3=0 execute.sh
qsub -o ~/HPC/code/parallel/logs/fast/n8 -e ~/HPC/code/parallel/logs/fast/n8 -v ARG1=7500,ARG2=8,ARG3=0 execute.sh
qsub -o ~/HPC/code/parallel/logs/fast/n8 -e ~/HPC/code/parallel/logs/fast/n8 -v ARG1=10000,ARG2=8,ARG3=0 execute.sh
qsub -o ~/HPC/code/parallel/logs/fast/n8 -e ~/HPC/code/parallel/logs/fast/n8 -v ARG1=10000,ARG2=8,ARG3=0 execute.sh
qsub -o ~/HPC/code/parallel/logs/fast/n8 -e ~/HPC/code/parallel/logs/fast/n8 -v ARG1=10000,ARG2=8,ARG3=0 execute.sh
