qsub -o ~/HPC/code/parallel/logs/n8 -e ~/HPC/code/parallel/logs/n8 -v ARG1=200,ARG2=8,ARG3=1 execute.sh
qsub -o ~/HPC/code/parallel/logs/n8 -e ~/HPC/code/parallel/logs/n8 -v ARG1=200,ARG2=8,ARG3=1 execute.sh
qsub -o ~/HPC/code/parallel/logs/n8 -e ~/HPC/code/parallel/logs/n8 -v ARG1=200,ARG2=8,ARG3=1 execute.sh
qsub -o ~/HPC/code/parallel/logs/n8 -e ~/HPC/code/parallel/logs/n8 -v ARG1=500,ARG2=8,ARG3=1 execute.sh
qsub -o ~/HPC/code/parallel/logs/n8 -e ~/HPC/code/parallel/logs/n8 -v ARG1=500,ARG2=8,ARG3=1 execute.sh
qsub -o ~/HPC/code/parallel/logs/n8 -e ~/HPC/code/parallel/logs/n8 -v ARG1=500,ARG2=8,ARG3=1 execute.sh
qsub -o ~/HPC/code/parallel/logs/n8 -e ~/HPC/code/parallel/logs/n8 -v ARG1=700,ARG2=8,ARG3=1 execute.sh
qsub -o ~/HPC/code/parallel/logs/n8 -e ~/HPC/code/parallel/logs/n8 -v ARG1=700,ARG2=8,ARG3=1 execute.sh
qsub -o ~/HPC/code/parallel/logs/n8 -e ~/HPC/code/parallel/logs/n8 -v ARG1=700,ARG2=8,ARG3=1 execute.sh
qsub -o ~/HPC/code/parallel/logs/n8 -e ~/HPC/code/parallel/logs/n8 -v ARG1=1000,ARG2=8,ARG3=1 execute.sh
qsub -o ~/HPC/code/parallel/logs/n8 -e ~/HPC/code/parallel/logs/n8 -v ARG1=1000,ARG2=8,ARG3=1 execute.sh
qsub -o ~/HPC/code/parallel/logs/n8 -e ~/HPC/code/parallel/logs/n8 -v ARG1=1000,ARG2=8,ARG3=1 execute.sh