qsub -o ~/HPC/code/distributed/logs/scatter/n2 -e ~/HPC/code/distributed/logs/scatter/n2 -v ARG1=16000,ARG2=4,ARG3=3 execute2scatter.sh
qsub -o ~/HPC/code/distributed/logs/scatter/n2 -e ~/HPC/code/distributed/logs/scatter/n2 -v ARG1=16000,ARG2=4,ARG3=3 execute2scatter.sh
qsub -o ~/HPC/code/distributed/logs/scatter/n2 -e ~/HPC/code/distributed/logs/scatter/n2 -v ARG1=16000,ARG2=4,ARG3=3 execute2scatter.sh
qsub -o ~/HPC/code/distributed/logs/scatter/n2 -e ~/HPC/code/distributed/logs/scatter/n2 -v ARG1=32000,ARG2=4,ARG3=3 execute2scatter.sh
qsub -o ~/HPC/code/distributed/logs/scatter/n2 -e ~/HPC/code/distributed/logs/scatter/n2 -v ARG1=32000,ARG2=4,ARG3=3 execute2scatter.sh
qsub -o ~/HPC/code/distributed/logs/scatter/n2 -e ~/HPC/code/distributed/logs/scatter/n2 -v ARG1=32000,ARG2=4,ARG3=3 execute2scatter.sh
qsub -o ~/HPC/code/distributed/logs/scatter/n2 -e ~/HPC/code/distributed/logs/scatter/n2 -v ARG1=64000,ARG2=4,ARG3=3 execute2scatter.sh
qsub -o ~/HPC/code/distributed/logs/scatter/n2 -e ~/HPC/code/distributed/logs/scatter/n2 -v ARG1=64000,ARG2=4,ARG3=3 execute2scatter.sh
qsub -o ~/HPC/code/distributed/logs/scatter/n2 -e ~/HPC/code/distributed/logs/scatter/n2 -v ARG1=64000,ARG2=4,ARG3=3 execute2scatter.sh