qsub -o ~/HPC/code/distributed/logs/first -e ~/HPC/code/distributed/logs/first -v ARG1=5000,ARG2=2,ARG3=3 execute.sh
qsub -o ~/HPC/code/distributed/logs/first -e ~/HPC/code/distributed/logs/first -v ARG1=5000,ARG2=2,ARG3=3 execute.sh
qsub -o ~/HPC/code/distributed/logs/first -e ~/HPC/code/distributed/logs/first -v ARG1=5000,ARG2=2,ARG3=3 execute.sh
qsub -o ~/HPC/code/distributed/logs/first -e ~/HPC/code/distributed/logs/first -v ARG1=5000,ARG2=4,ARG3=3 execute.sh
qsub -o ~/HPC/code/distributed/logs/first -e ~/HPC/code/distributed/logs/first -v ARG1=5000,ARG2=4,ARG3=3 execute.sh
qsub -o ~/HPC/code/distributed/logs/first -e ~/HPC/code/distributed/logs/first -v ARG1=5000,ARG2=4,ARG3=3 execute.sh
qsub -o ~/HPC/code/distributed/logs/first -e ~/HPC/code/distributed/logs/first -v ARG1=5000,ARG2=8,ARG3=3 execute.sh
qsub -o ~/HPC/code/distributed/logs/first -e ~/HPC/code/distributed/logs/first -v ARG1=5000,ARG2=8,ARG3=3 execute.sh
qsub -o ~/HPC/code/distributed/logs/first -e ~/HPC/code/distributed/logs/first -v ARG1=5000,ARG2=8,ARG3=3 execute.sh